#!/bin/sh /etc/rc.common

USE_PROCD=1
START=95
STOP=5

PROG=/usr/bin/3proxy
CONFIG_FILE=/etc/config/3proxy.cfg

start_service() {
    procd_open_instance
    procd_set_param command "$PROG" "$CONFIG_FILE"
    procd_set_param respawn 3600 5 0
    procd_close_instance
}

stop_service() {
    # 3proxy in daemon mode handles its own stopping via pid file
    # Or, if you prefer, you can send a kill signal
    killall 3proxy
    return 0
}

reload_service() {
    # 3proxy can be reloaded by sending a HUP signal
    # kill -HUP $(cat /var/run/3proxy.pid)
    # Since procd is managing it, a restart is often simpler
    stop_service
    start_service
}
